### ISSUE TITLE
tcR package will soon be orphaned

### ISSUE THREAD

**Issue by vadimnazarov** [BioTesseract/kmeRs#3]
Hi @RafalUrniaz ,

thank you for supporting the RepSeq community with your package! I would like to notify you that the tcR package will soon be orphaned in favour of our new package immunarch - https://github.com/immunomind/immunarch

I would be glad to help you move to the immunarch dependency. 

What parts of tcR do you use?

**Comment by vadimnazarov** [comment]
Hi @RafalUrniaz 

The `immunarch` is on CRAN now, so you can freely test the compatability!

**Comment by RafalUrniaz** [comment]
Hi @vadimnazarov 

Thank you for your support! We will switch and test `kmeRs` package for compatibility with `immunarch` asap. Thanks!

**Comment by vadimnazarov** [comment]
Thank you Rafal! And please let me know if you have any questions, we will be happy to help at immunomind/immunarch
